In [1]:
#importing the libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
datasets=pd.read_csv("Social_Network_Ads.csv")

In [3]:
datasets

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
datasets=pd.get_dummies(datasets,drop_first=True)

In [5]:
datasets

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=datasets[['Age', 'EstimatedSalary','Gender_Male']]
dep=datasets['Purchased']

In [7]:
indep

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [8]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.svm import SVC

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear','rbf','poly','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,100,1000,2000,3000]} 



grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

Fitting 3 folds for each of 40 candidates, totalling 120 fits

[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    2.4s
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    3.8s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9171245421245421

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[73  6]
 [ 4 37]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005207,0.007364,0.000000,0.000000,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.784017,0.739369,0.900383,0.807838,0.067766,29
1,0.005207,0.007364,0.000000,0.000000,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.893617,0.861345,0.946396,0.900428,0.034997,1
2,0.005207,0.007364,0.000000,0.000000,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.858980,0.801769,0.923274,0.861333,0.049544,9
3,0.005207,0.007364,0.000000,0.000000,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.691578,0.731982,0.761828,0.728331,0.028820,39
4,0.005207,0.007364,0.000000,0.000000,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.784017,0.739369,0.900383,0.807838,0.067766,29
5,0.000000,0.000000,0.000000,0.000000,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.893617,0.861345,0.935484,0.896804,0.030298,2
6,0.005207,0.007363,0.005207,0.007363,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.858980,0.801769,0.923274,0.861333,0.049544,9
7,0.000000,0.000000,0.000000,0.000000,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.691578,0.731982,0.751882,0.725027,0.025124,40
8,0.010414,0.007364,0.005207,0.007364,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
9,0.010414,0.007364,0.000000,0.000000,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.893617,0.872288,0.924486,0.896786,0.021390,3
10,0.010414,0.014728,0.005207,0.007364,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.847403,0.801769,0.900383,0.849843,0.040224,13
11,0.005207,0.007364,0.005207,0.007364,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.736252,0.722014,0.798176,0.752090,0.033017,37
12,0.005207,0.007364,0.000000,0.000000,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
13,0.005207,0.007364,0.000000,0.000000,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.893617,0.872288,0.924486,0.896786,0.021390,3
14,0.015621,0.012755,0.000000,0.000000,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.847403,0.801769,0.900383,0.849843,0.040224,13
15,0.000000,0.000000,0.005207,0.007364,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.736252,0.722014,0.798176,0.752090,0.033017,37
16,0.056023,0.008604,0.000665,0.000940,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
17,0.007201,0.006435,0.000333,0.000470,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.882589,0.861345,0.844205,0.862784,0.015717,5
18,0.076926,0.045390,0.000000,0.000000,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.835667,0.801769,0.900383,0.845903,0.040840,15
19,0.000000,0.000000,0.000000,0.000000,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.746165,0.722014,0.798176,0.755418,0.031727,31
20,0.061305,0.013484,0.001625,0.002298,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
21,0.005207,0.007364,0.005207,0.007364,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.882589,0.861345,0.844205,0.862784,0.015717,5
22,0.053830,0.015322,0.000332,0.000470,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.835667,0.801769,0.900383,0.845903,0.040840,15
23,0.000665,0.000470,0.000655,0.000464,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.746165,0.722014,0.798176,0.755418,0.031727,31
24,0.228458,0.125611,0.005207,0.007364,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
25,0.005207,0.007364,0.000000,0.000000,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.893617,0.861345,0.832123,0.862473,0.025140,7
26,0.135960,0.066492,0.000000,0.000000,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.835667,0.801769,0.900383,0.845903,0.040840,15
27,0.005207,0.007364,0.000000,0.000000,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.746165,0.722014,0.798176,0.755418,0.031727,31
28,0.195554,0.092297,0.010414,0.007364,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
29,0.006832,0.009662,0.000681,0.000964,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.893617,0.861345,0.832123,0.862473,0.025140,7
30,0.126489,0.090083,0.000000,0.000000,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.835667,0.801769,0.900383,0.845903,0.040840,15
31,0.005207,0.007364,0.000000,0.000000,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.746165,0.722014,0.798176,0.755418,0.031727,31
32,0.354561,0.302497,0.000000,0.000000,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
33,0.010414,0.007364,0.000000,0.000000,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.872340,0.851533,0.830023,0.851374,0.017291,11
34,0.161424,0.053101,0.005203,0.007358,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.835667,0.801769,0.900383,0.845903,0.040840,15
35,0.000000,0.000000,0.000000,0.000000,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.746165,0.722014,0.798176,0.755418,0.031727,31
36,0.307112,0.248595,0.000000,0.000000,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.784017,0.739369,0.911897,0.811662,0.073004,21
37,0.015610,0.000016,0.000000,0.000000,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.872340,0.851533,0.830023,0.851374,0.017291,11
38,0.166627,0.082987,0.000000,0.000000,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.835667,0.801769,0.900383,0.845903,0.040840,15
39,0.005207,0.007364,0.000000,0.000000,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.746165,0.722014,0.798176,0.755418,0.031727,31